### ISSUE TITLE
Add translation to Portuguese Brazil

### ISSUE THREAD

**Issue by TiagoDanin** [nodejs/i18n#110]
Reasons:
- ~3.49% of site visitors were Brazilian ([Source](https://github.com/nodejs/website-redesign/issues/15#issuecomment-369827787)).
- Syntax and pronounce is extremely different from Pt-PT
----
Cc @nodejs/nodejs-pt

**Comment by zeke** [comment]
> pronounce is extremely different

For written language that shouldn't matter though, right?

I'm happy to enable this Brazilian Portugues, but would like to hear from some other Portuguese speakers first. My only hesitation is because I enabled Venezuelan Spanish on the Electron project (by request from one person), and a bunch of Spanish language translators protested, saying the differences were not significant enough to justify having "Spanish" and "Venezuelan Spanish". Like I said though, happy to enable it if people think it makes sense.

**Comment by JCMais** [comment]
Brazilian Portuguese has enough differences from Portugal Portuguese to make this a reasonable request. 

Tho, the differences are more evident on informal writing, I don't if they are going to be that big on technical/formal writing.

**Comment by TiagoDanin** [comment]
> For written language that shouldn't matter though, right?

Writing is different for some word and other not. The language is a mixture of the Portuguese of Porgutal with the natives languages of the ancient peoples.

**Comment by FranzDeCopenhague** [comment]
How much is the difference regarding to technical documentation?

**Comment by gustavohenke** [comment]
> How much is the difference regarding to technical documentation?

Back when the only thing @nodejs/nodejs-pt did was a portuguese blog, I would still feel not comfortable reading posts written by portuguese folks. I would consider these quite technical.
