### ISSUE TITLE
i18n: document how to fix issues

### ISSUE THREAD

**Issue by srl295** [nodejs/i18n#18]
As mentioned in https://github.com/nodejs/i18n/pull/14#issue-169523231 — Incorporate https://github.com/nodejs/node/wiki/Intl#q-how-do-the-pieces-fit-together--how-do-i-know-who-is-responsible-for-the-bug into node docs ( possibly https://nodejs.org/api/intl.html or elsewhere ). 

Example: https://github.com/unicode-org/full-icu-npm/issues/21#issue-287273095 "the thousands separator is not what I expect"

**Comment by zeke** [comment]
Might be going on a tangent here, but regarding the numerical separator, there's a browser API for it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

We could have a website build process that finds numbers in plaintext, wraps them in something like `<span class="number" data-value="1000000">1,000,000<span>`, and lets some browser code do the work of reformatting for the visitor's locale.

**Comment by srl295** [comment]
@zeke the bug above is someone using that exact API and not being happy with the result.

The suggestion is interesting, however, it could result in output that's doesn't match the surrounding content.   For example, suppose you have my twitter/github handle  `@srl295`. It might turn into `@srl二百九十五` or `@srl٢٩٥` on such a page. Really, you want output to harmonize with the page's language.  However, something displaying statistics (let's say) that is also localized to some language, could use your technique to make sure the values match your language.

**Comment by zeke** [comment]
The project doesn't use GitHub wikis any more, so the above-mentioned content no longer exists in Wiki format. As your recommendation is to include such guidelines in https://nodejs.org/api/intl.html, I would suggest opening an issue on nodejs/node, where that source content lives.

Going to close on the basis that this issue is inactive, doesn't have a clear solution, and probably should be resolved in another repo, but feel free to re-open this issue if I'm out of bounds.
