### ISSUE TITLE
i18n WG Meeting - Feb 14

### ISSUE THREAD

**Issue by maddhruv** [nodejs/i18n#209]
### Date & Time
- 5:00 pm GMT on Feb 14, 2020

### Links
- [Zoom link](https://zoom.us/j/307660555)
- [Google Docs Minutes](https://docs.google.com/document/d/1pV7NpXE429qw_T7BL6TZGVkL9Pyn9UkJ1_67hzvFtvs/edit?usp=sharing)

### Agenda
- Unblock translation process - https://github.com/nodejs/nodejs.org/issues/2906
- Intl vs i18n - https://github.com/nodejs/TSC/issues/813
- website content to be translated - https://github.com/nodejs/i18n/issues/72
- i18n WG Meeting Time & Frequency - https://github.com/nodejs/i18n/issues/34
- Publish a module to npm - https://github.com/nodejs/i18n/issues/92
- Audit of our l10n groups - https://github.com/nodejs/i18n/issues/19
- automatic approve and merge translation PRs - https://github.com/nodejs/i18n/issues/161
- Create Crowdin Glossary - https://github.com/nodejs/i18n/issues/81 / https://github.com/nodejs/i18n/pull/91
- In case I missed something - https://github.com/nodejs/i18n/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Ai18n-agenda

### Invited Members
- @nodejs/i18n 
- @nodejs/website-redesign 
- @nodejs/community-committee 
- @nodejs/tsc 
- @nodejs/website

**Comment by nschonni** [comment]
Should the regular website team also be invited? They're impacted by the first agenda item

**Comment by maddhruv** [comment]
Sure, included :+1:

**Comment by obensource** [comment]
@maddhruv @nschonni imo, we should overlap soon – but for this next i18n WG meeting, there's going to be enough logistics to cover to get the i18n WG back in sync, etc, that it would probably be better time spent joining us at the next WG meeting with website i18n on the agenda. Y'all should join if you'd like and might get something out of it, but just fyi (this is kind of a 'regroup' meeting since there's a bit of time has passed since we last met).

**Comment by obensource** [comment]
@zeke! If you're able, come join us! 🙌🎉🍻

**Comment by obensource** [comment]
@srl295 if you're able, please join us! It would be awesome to have your amazing wizardry with us to help push things forward! 🧙‍♂️

![research](https://user-images.githubusercontent.com/1910457/73775717-471dcf80-473b-11ea-9a4b-c2f44428e517.png)

**Comment by zeke** [comment]
Thanks for the ping. I doodled.

**Comment by RichardLitt** [comment]
So, we have our dates, but we didn't decide on a process for dealing with times for when there is no consensus. I'm leaning towards the February the 14th time, if only because I know that @Zeke has been instrumental. @TiagoDanin Is there any way you can make that time?

**Comment by RichardLitt** [comment]
Looks like I also failed to set an end-date. Thanks for filling this out, Aymen. At the moment, it seems that the 14th is the best day for the most people. Shall we go with that time, everyone?

**Comment by obensource** [comment]
@RichardLitt sounds great, looks like that's what works best for everyone – let's do it! 🎉

Thanks for wrangling us together via doodle! 🙏

**Comment by TiagoDanin** [comment]
> @TiagoDanin Is there any way you can make that time?

I'll do my best, but I’m not promising anything :smiley:

**Comment by RichardLitt** [comment]
Awesome. See you all there! 

Does anyone have a paid Zoom account? Mine would cap us at 40 minutes, which might be a good idea anyway.

**Comment by obensource** [comment]
@RichardLitt Wahoo! See you there! 🙌

@bnb – can we use the node.js zoom account? Would be fun to capture & stream if possible. 😄

**Comment by bnb** [comment]
@obensource yes. Currently on a train but ping me on Slack so I can get you the credentials.

**Comment by obensource** [comment]
@bnb RAD will do! Thanks a million! 🙏

**Comment by maddhruv** [comment]
Literally forgot to create a calendar event, added now - [calendar event]( https://calendar.google.com/event?action=TEMPLATE&tmeid=MDZzaWxiaXA0cG5zZTlzbDUxOWdvMXNoanMgbm9kZWpzLm9yZ19ucjc3YW1hOHA3ZDdmOWFqcnBudTUwNmM5OEBn&tmsrc=nodejs.org_nr77ama8p7d7f9ajrpnu506c98%40group.calendar.google.com)

**Comment by obensource** [comment]
Haven't been able to receive the node zoom credentials yet, not a big deal if not – I'll share a zoom link shortly before the meeting regardless, record the meeting, and post it on our YT channel in post if needed. 👍

cc @bnb (thanks for your help! 🙏)

**Comment by obensource** [comment]
Got the creds from @bnb, getting YT access for streaming now as well – will share the link shortly. 👍

**Comment by RichardLitt** [comment]
Fantastic. Thanks @bnb.

**Comment by obensource** [comment]
Zoom link unlocked! [Here it is](https://zoom.us/j/307660555)! 🎉

**Comment by obensource** [comment]
@maddhruv I noticed that the permissions on the minutes doc weren't set (read only), so I made a new one with edit access for everyone and updated the link in the issue description. 👍

**Comment by maddhruv** [comment]
I am very sorry, could't attend the meeting, got stuck into something unavoidable. 😣😣

**Comment by alexandrtovmach** [comment]
Hello guys,
Unfortunately, I haven't time to join but I'm really interested in questions that you discussed. So I've checked [report](https://docs.google.com/document/d/1pV7NpXE429qw_T7BL6TZGVkL9Pyn9UkJ1_67hzvFtvs/edit?usp=sharing) and just want to let you know, I'd like to help with translations process.
I'd like to share my vision of steps:

1. As you mentioned, we already had a lot of translated stuff on Crowdin side, but it's not correctly connected to nodejs repos, and that's the first step before we move forward. We can talk more about that here https://github.com/nodejs/nodejs.org/issues/2906. I just need this API keys to fix **Nodejs<->Crowdin** connection.

2. Second thing, is awesome to give a bit more info about "how to contribute for translators", but I think we need to brainstorm one more time, because we can have different ideas how it's should be. Somewhere in 2019 I tried to handle all translation flow (but faced with blockers), so I have some not realized plan like: "all translations should be on Crowdin side, and automated by hooks, PR and CI/CD".

3. We still haven't configured CI/CD to build website, docs on different languages

Sorry for the randomness and errors, writing from phone (I'm testing github android app =)). Hope to get off the ground, and see you soon on next meeting

**Comment by zeke** [comment]
Eek! Sorry I missed this meeting, y'all.

I would love to attend the next one. Unfortunately, I don't think I can make it to that 10:30pm Pacific time slot. I'm usually offline (and asleep!) by that time. If it's possible to do another doodle that would make my chances of attendance much higher.

**Comment by obensource** [comment]
@zeke oh, sorry if there's been a miscommunication! We're meeting weekly on Fridays at 10am PT (6pm UTC) at the moment. 👍

**Comment by obensource** [comment]
We'll likely need to do a bi-monthly or monthly meeting at a time that's ideal globally like that as well in order to make this group accessible to everyone.

**Comment by obensource** [comment]
I'll get a reoccurring calendar invite going for everyone asap. 🙌

**Comment by obensource** [comment]
Accidentally closed this issue (on mobile), however the meeting is passed so I guess it's ok. @alexandrtovmach so excited to get things moving with your and very thankful for your continued help! 🙌

**Comment by zeke** [comment]
> We're meeting weekly on Fridays at 10am PT 

Nice! I have a conflict this week, but that's generally a good time slot for me. 👍
