### ISSUE TITLE
i18n (Russian)

### ISSUE THREAD

**Issue by seirina-of-js** [nodejs/i18n#211]
I'd love to get involved and help with English-Russian translations :)

**Comment by seirina-of-js** [comment]
I also could take responsibility for reviewing others' translations for this very language pair, as I used to work as a translator before.

**Comment by nschonni** [comment]
Ping @nodejs/nodejs-ru

**Comment by seirina-of-js** [comment]
@nschonni I guess I have no access. It gives back 404

**Comment by seirina-of-js** [comment]
@nschonni It appears this one https://github.com/nodejs/nodejs-ru is archived and no longer maintained...

**Comment by nschonni** [comment]
It's the `@` for the Russian localization GitHub team for Node, so they'll get a notification to take a look at this issue

**Comment by seirina-of-js** [comment]
@nschonni ah, okay. Thanks :)

**Comment by alexandrtovmach** [comment]
@seirina-of-js As you already know, we are trying to fix the translation process now

Yeah, https://github.com/nodejs/nodejs-ru archived, and I can unarchive it, but seems like it's no longer needed, because all translation management going to be on Crowdin side, so this repo is just for some instructions and community connection.
