### ISSUE TITLE
Translation l10n to Hindi

### ISSUE THREAD

**Issue by maddhruv** [nodejs/i18n#32]
The current repo for Hindi translation and l10n is not maintained any more - https://github.com/nodejs/nodejs-hi
Please allow me to take over the repo and form a team for i18n Hindi translators and collaborators.

**Comment by lukaszewczak** [comment]
Hi @maddhruv  that's great that you'd like to get the Hindi l10n group going! I recommend reaching out to existing team https://github.com/nodejs/nodejs-hi#team and seeing if they are still interested in helping out with that as well. You could then start collaborating on that existing repo.

The problem could be in situation when there will be no contact from the current team, at the moment I do not know how this situation will be handled but this should be clarified soon after our group audits the l10n groups.

**Comment by obensource** [comment]
### Rebuilding nodejs-hi
Hi @maddhruv if you're interested in resurrecting and building the Hindi l10n group up, that sounds really awesome! I agree with @lukaszewczak that it would be a good idea to reach out to the people who were previously involved and see if there's anyone who's still interested in helping out with maintaining and growing that group, as well as adding you as a member and/or lead maintainer.

In the i18n WG, we don't maintain a central authority to allow or disallow members to join or take ownership of l10n groups. Rather we are of equal authority, and exist alongside as a way for every l10n group to get their work into Node.js. So, none of us in i18n can grant you permission to 'take over' a group.

Another path this could take for `nodejs-hi`, is if no one responds to you after reaching out to them and the group is truly dead–you could request that the group be dechartered in [`nodejs/admin`](https://github.com/nodejs/admin/issues/new) and build & champion your own group from the ground up. 🙂

### Getting involved with the i18n WG
I noticed that you requested to join our [i18n team](https://github.com/orgs/nodejs/teams/i18n/members). I just want to ask before I add you–if you're interested in joining the WG in order to build the Hindi l10n group? Or, are you interested in helping us with i18n efforts like setting up setting up the services and modules that enable i18n in Node.js? Or both? I'm super excited to have you join this effort in any capacity–I just want to make sure you know that you don't have to join the i18n WG in order to push the l10n Hindi group effort forward because i18n will be trying to provision what you need in order for you to land your work in Node.

Thanks a bunch @maddhruv! 🍻

**Comment by maddhruv** [comment]
I will get in touch with the current members of the group, but it seems the team is scattered now.

Moreover @obensource I am interested in joining the **WG** and build a Hindi l10n group and help the community with i18n.
I request you to add me to i18n as well as WG

**Comment by obensource** [comment]
@maddhruv awesome! Sounds great. 🙌

Though it seems scattered, I'm excited to see if anyone is interested in joining in with you in the l10n group–and either way, I know that you'll spearhead something really awesome with Hindi l10n. Thank you for stepping forward and making this happen! 🎉🎉🎉

Thank you for joining us in i18n, I'll go ahead an add you. Excited to talk more! 🍻

**Comment by obensource** [comment]
@maddhruv please close this issue as you see fit. :)
