### ISSUE TITLE
Publish the current module to npm

### ISSUE THREAD

**Issue by bnb** [nodejs/i18n#328]
Currently the [npm package](https://github.com/nodejs/i18n/blob/master/guides/NPM_PACKAGE.md) instructions require installation from GitHub.

I'd like to see this module published to GitHub within the Node.js scope. Given the repo name and the module purpose, I think `@nodejs/i18n` is appropriate? Open to suggestions but I think it's a reasonable scope.

I'm not sure who controls the `@nodejs` scope, but if publishing to that scope is reasonable to y'all we can ping a few folks who will know.

**Comment by zeke** [comment]
Having test-driven the GitHub-hosted module, I've already run into a few snags. In my case, I was unable to install the module in a GitHub Action because I was using a node-alpine container image. Took me a while to figure out that those images don't include `git`, and that git is what's used by `npm` under the hood to install GitHub-based dependencies.

I'd be happy to help set this up once we land on a package name. If we can use the `@nodejs` scope and name it `@nodejs/i18n`, I think that would be great.

**Comment by bnb** [comment]
cc @mhdawson @MylesBorins - do y'all know the correct avenue to getting something published under the `@nodejs` scope?

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
