### ISSUE TITLE
Versions to Translate

### ISSUE THREAD

**Issue by maddhruv** [nodejs/i18n#71]
Targeted versions to be translated into #70 
Primarily --
- [v4.x] - EOL - 04/18 - **M. LTS** :hourglass: 
- [v5.x] - EOL :skull: 
- [v6.x] - EOL - 04/19 - **A. LTS**
- [v7.x] - EOL :skull: 
- [v8.x] - EOL - 12/19 - **A. LTS**
- [v9.x] - EOL - 06/18 :hourglass: 
- [v10.x] - A. LTS - 10/18 :birthday: 

Which all versions shall we be targeting for translations?
5/7 are dead, 4 is used at many places but LTS gonna  die soon

Refer - https://nodejs.org/dist/index.json

**Comment by zeke** [comment]
I like the idea of this repo only having the freshest docs for each major version of node. Following the lead of the [existing website](https://nodejs.org/en/docs/#api-reference-documentation) and @maddhruv's example above, I'd be in favor of naming the content directories `v<MAJOR>.x` instead of using specific version numbers.

```
content
├── v10.x
├── v6.x
├── v7.x
├── v8.x
└── v9.x
```

It will take some work to get the build process to gracefully overwrite existing docs as new minors and patches are imported, but we can figure it out. We can use Crowdin's Translation Memory workflows to fill in existing translations as new content comes in. See https://github.com/nodejs/i18n/issues/56
