### ISSUE TITLE
Set up the Crowdin-GitHub integration together, and record it

### ISSUE THREAD

**Issue by zeke** [nodejs/i18n#77]
Since we haven't yet set up our Crowdin-GitHub integration, I was thinking we could walk through it together in our next working group meeting.

As a prerequisite, we'd need to make the @nodejs-crowdin GitHub user the new owner of https://crowdin.com/project/nodejs, instead of @obensource. That will allow multiple members of our working group to log in an administer the account. @andrulko are you able to make this change for us?

PS When is our next meeting?

**Comment by obensource** [comment]
@zeke my boss just assured me that I can spend a bit of time each week supporting our great work here–and joining in our meetings! Wahoo!

Let's schedule our next meeting asap and get this going. 🎉

**Comment by Andrulko** [comment]
Hey @zeke and @obensource!

Just made the first step, main account is renamed to **nodejs-crowdin**:
https://crowdin.com/profile/nodejs-crowdin

@obensource, it's still linked with your email address and you may change the avatar/email address in the profile settings:
https://crowdin.com/settings#account

Afterward, create new **obensource** account [here](https://crowdin.com/join) and assign yourself as a manager.

Create @nodejs-crowdin user on GitHub, then log in under **nodejs-crowdin** main account and setup GitHub integration from @nodejs-crowdin GitHub user name. It sounds complicated as I see, but it should be very easy 😉 I'm always ready to join the meeting with you to assist with setup!

**Comment by amor520** [comment]
so nice, joined nodejs-crowdin !

**Comment by ryo-a** [comment]
the icon of [nodejs-crowdin](https://crowdin.com/profile/nodejs-crowdin) is still obensource's one.
it is desirable that someone (has permission) change the icon.

**Comment by Andrulko** [comment]
It is a great avatar I must say! But if necessary, @obensource can update profile picture here:
https://crowdin.com/settings#account

**Comment by zeke** [comment]
Hey @Andrulko I just logged in to Crowdin using GitHub OAuth with the GitHub user @nodejs-crowdin for which our group now has shared credentials.  It prompted me to "sign up", so I used this info:

<img width="507" alt="screen shot 2018-05-10 at 10 13 14 pm" src="https://user-images.githubusercontent.com/2289/39907806-d3a0b61a-549f-11e8-851c-0d8d76875db2.png">

Sorry for the confusion, but can you update the `nodejs` crowdin project to use this new user as the owner?

**Comment by Andrulko** [comment]
Hey @zeke,

The **nodejs-crowdin** username was earlier taken by @obensource, thus you were prompted to specify another username.

I will contact you privately and help to link GitHub OAuth with existing account

**Comment by FranzDeCopenhague** [comment]
This is great! https://crowdin.com/project/nodejs

I have found another project at crowdin https://crowdin.com/project/nodejs_ru Is it related to our i18n group?

**Comment by zeke** [comment]
> Is it related to our i18n group?

Not that I know of.

cc @artcygn who appears to be the owner. 👋

**Comment by zeke** [comment]
Earlier today, I attempted to connect the @nodejs-crowdin GitHub user to Crowdin, but had to request access.

@bnb or @rvagg do you know who might have received this request?

<img width="606" alt="screen shot 2018-05-15 at 7 54 44 am" src="https://user-images.githubusercontent.com/2289/40085391-1b31bce2-584f-11e8-9916-d221fbcea57b.png">

<img width="594" alt="screen shot 2018-05-15 at 7 54 51 am" src="https://user-images.githubusercontent.com/2289/40085392-1e546208-584f-11e8-8c88-533217527fe8.png">

**Comment by rvagg** [comment]
Yeah, so this is where we break down, if they need org access with that "request" button then it goes to org owners (TSC++) and we have a general rule of not giving access to third-party services. We've been using the nodejs-github-bot to work around this for various things.

> @nodejs-crowdin has requested approval for a third-party application to access Node.js Foundation organization resources via the GitHub API:
>
>  "Crowdin" from crowdin
>
> Until it is approved, this application will have no access to private resources and will have read-only access to public resources belonging to your organization.

Perhaps the TSC would be more comfortable giving access to the org now that we've moved most of the sensitive private repos to a new org. Although I think we still have some (like moderation?), and the easy-path for security has just been a blanket _no_ to third-party access. Are you able to get more information on what this requires from the org and what kind of access it'll actually have? Will it be limited to only what we give @nodejs-crowdin access to or if the org owners give this permission does that mean it has permission to reach in more deeply, beyond what @nodejs-crowdin has access to?

**Comment by zeke** [comment]
> Are you able to get more information on what this requires from the org and what kind of access it'll actually have? 

☝️I'll defer to @Andrulko from Crowdin for a definitive answer to this.

**Comment by Trott** [comment]
FYI, I used the "deny access" button on the request just like for everything else that's ever requested access to private info. But there's absolutely no reason someone (including me) can't edit the entry for this integration to grant access once all the info is gathered and the TSC gives a :+1: on it.

**Comment by zeke** [comment]
As I understand it, the new @nodejs-crowdin GitHub account only has admin access to a single repo `nodejs/i18n`, so the vulnerable surface area is quote low. @rvagg is that correct?

> grant access once all the info is gathered and the TSC gives a 👍 on it.

I am unfamiliar with the TSC's process. Please let me know if there's something I can do to help move the process forward.

**Comment by Trott** [comment]
> I am unfamiliar with the TSC's process. Please let me know if there's something I can do to help move the process forward.

Looks like someone already added the bot to this repository so I don't think there's anything for the TSC to do, unless you needed it added org-wide or something like that.

**Comment by zeke** [comment]
Here's what I see now:

<img width="578" alt="screen shot 2018-05-21 at 4 15 04 pm" src="https://user-images.githubusercontent.com/2289/40334362-2791e044-5d12-11e8-8c6c-ffcce85321b7.png">

> someone already added the bot to this repository so I don't think there's anything for the TSC to do

I'm not sure I understand where that leaves us. What are our options at this point for giving Crowdin organization access?

**Comment by Trott** [comment]
@zeke Are you not able to use the "Authorize crowdin" button in the screenshot you provide. IIUC, that will give the plugin access to the @nodejs-crowdin account which, as far as I know, has admin access in this repository but nothing else in the nodejs org. So that might be all you need? (Also, you might consider reducing the account's privileges to Write rather than Admin if it only needs read/write.)

> I'm not sure I understand where that leaves us. What are our options at this point for giving Crowdin organization access?

@zeke If the plugin needs org access rather than merely access to this repository, you need TSC approval. (If all you need is access to this repository only, then I think you're already all set.)

You can add the tsc-agenda label to this issue and it will automatically be added to the agenda for the next TSC meeting. If you want to get it on this week's TSC agenda, request that it be added in the issue for this week's meeting which is https://github.com/nodejs/TSC/issues/544.

Three things to try to make things go smoothly:

* Identify an informed advocate who can answer questions and ask that they be invited to the meeting as a guest. In this case, it might be @zeke or maybe someone else.

* Provide a short (one paragraph if possible, but sometimes things just can't be kept that short) summary to address likely questions that will come up. The TSC is likely to ask questions about exactly what the user will have access to and why there needs to be org-wide read/write access granted if the plugin just needs to read/write to a single repo. That sort of thing.

* Identify an appropriate person on the TSC who might be able and willing to understand everything ahead of time and therefore advocate at the meeting. For GitHub permissions stuff, I think @rvagg, @targos, and @gibfahn tend to have a baseline understanding and care enough to dig in and understand what's going on, at least when they have time to do so. There are no doubt others in the group. And then there are people like me, who understand just enough about GitHub plugin permissions to be able to ask annoying questions and delay things because of our own ignorance. We're the people you're trying to put at ease.

Hope this helps and sorry if it seems like a whole bunch of unnecessary work. These policies/rules were formulated when there was more information that was sensitive in the repositories within the nodejs org than there is at the current time. It's possible they should be updated. If so, pull requests with proposals are welcome. (Or open an issue in the TSC or admin repos.)

**Comment by Trott** [comment]
(Oh, I think I see: the org settings override the account privs and the plugin can't write to this repository? If that's right, then unfortunately that will probably require escalation to the TSC as described in the longer part of my answer. Sorry.)

**Comment by zeke** [comment]
Thanks for breaking it down, @Trott 👍 

I labeled this issue and made a plea for the next TSC meeting: https://github.com/nodejs/TSC/issues/544#issuecomment-390859048

**Comment by mcollina** [comment]
@zeke can you please update this issue with a lengthy "why" explanation. Why do we need crowdin, and what can we use this for, and also why it's needed for the tsc to approve this.

**Comment by rvagg** [comment]
So, I'm +1 on this on the proviso that this doesn't give the service more access than the nodejs-crowdin user does that we created for this. Even reading this thread I still don't have full confidence that this is the case. That's all I care about and I'm very confident that this is all the TSC cares about too.

**Comment by mcollina** [comment]
Which repo will this be used on? Only nodejs/i18n or something else as well?

**Comment by zeke** [comment]
> Only nodejs/i18n

Correct

> this doesn't give the service more access than the nodejs-crowdin user does that we created for this

Also correct, as long as no one gives @nodejs-crowdin admin or write access to any more repos.

**Comment by targos** [comment]
I suppose that if someone else from the org creates a crowdin account, that would automatically give them access to all repositories that user has access to? Could we somehow use the GitHub API to monitor it?

**Comment by Andrulko** [comment]
Yes, it might be true indeed. If another person from the org will setup Crowdin account and setup GitHub integration afterward, all repositories he/she has the access to will be available for Crowdin integration. If another repo was linked with Crowdin, automatic pull requests will be sent to this repo from our end and there will be `crowdin.yml` configuration file created in the connected branches.

Not sure about API to track such cases unfortunately, also I have doubts that trusted people in your community will connect other repositories with third-party services like Crowdin 😉

**Comment by fhinkel** [comment]
Unless I missed a comment, nobody is -1 on adding the Crowdin plugin?

**Comment by zeke** [comment]
It would be swell if we could unblock this before the Node.js Collaborator summit later this week.

**Comment by fhinkel** [comment]
Who's blocking it?

**Comment by zeke** [comment]
> Who's blocking it?

There's no individual blocking it. The TSC is just being (understandably) cautious about giving third-party access to the @nodejs GitHub org.

**Comment by zeke** [comment]
This happened! Recording forthcoming.
